spring:
  config:
    activate:
      on-profile:
        - test

  mail:
    host: localhost
    port: 3025
    username: tester@test.com
    password: tester
    transport:
      protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

---

spring:
  config:
    activate:
      on-profile:
        - local
        - dev
        - prod

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ADDRESS}
    password: ${GMAIL_PASSWORD}
    transport:
      protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true