name: tmeroom-spring-server CI / CD with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  setting_for_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out env files
        uses: actions/checkout@v3
        with:
          repository: TeamyRoom/TMeRoom-ServerEnv
          ref: master
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Upload env files
        uses: actions/upload-artifact@master
        with:
          name: env-file
          # 가져올 프로젝트의 설정 파일을 지정
          path: ./spring/application-prod.yml
          
  build:
    runs-on: ubuntu-latest
    needs: setting_for_build
    steps:
      # github action의 가상환경에 내 프로젝트를 체크아웃하기
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Download env files
        uses: actions/download-artifact@master
        with:
          name: env-file
          path: src/main/resources
          
      # github action의 가상환경에 빌드를 위해 jdk 17 설치하기
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # gradle로 빌드할 의존성 준비하기
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # gradle로 빌드하여 jar 파일 생성하기
      - name: Execute Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar

      # job은 별도의 가상환경에서 실행되므로
      # job 사이에 파일 공유를 위해 빌드 결과물인 jar 파일을 upload함
      - name: Upload jar file
        uses: actions/upload-artifact@master
        with:
          name: build-result
          path: ./build/libs

      - name: Upload Dockerfile
        uses: actions/upload-artifact@master
        with:
          name: Dockerfile
          path: ./Dockerfile

  # 참고 사이트
  # https://docs.github.com/ko/actions/publishing-packages/publishing-docker-images
  push_to_registry:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # 이전 job에서 업로드 한 jar 파일을 다운로드하여 docker image 생성 시 사용
      - name: Download jar file
        uses: actions/download-artifact@master
        with:
          name: build-result
          path: build/libs

      - name: Download Dockerfile
        uses: actions/download-artifact@master
        with:
          name: Dockerfile
          path: ./

# Github Secret과 local env 에 저장된 값 불러오기
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: tmeroom-spring
          IMAGE_TAG: ${{ github.run_number }}.${{ github.run_attempt }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

  deploy:
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:

      # github action의 IP가 수시로 바뀌므로
      # 그 ip를 ec2의 인바운드 규칙에서 허용해야 하므로
      # github action의 IP를 얻어온다.
      - name: Get Github Actions IP
        id: ip
        uses: haythem/public-ip@v1.3

      # ec2 IAM 계정의 access key, secret key의 계정정보 등록
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout for Kustomize repository
        uses: actions/checkout@v2
        with:
          # kubernetes yaml 파일 저장
          repository: TeamyRoom/TMeRoom-k8s-manifest # k8s yaml 파일이 있는 repo
          ref: main  # branch 이름
          # 내 repository에 push 하기 위한 Personal Access Token이 필요
          token: ${{ secrets.ACTION_TOKEN }} # Github Action token을 발급받아서 repo secrect에 등록해줘야한다
          path: TMeRoom-k8s-manifest # 최상위 경로로 repository와 동일하게 설정

          # 새 이미지 버전으로 파일의 태그값 수정
          # cd path 수정
          # kustomize로 image tag 값 변경
      - name: Update Kubernetes resources
        run: |
          pwd
          ls
          cd TMeRoom-k8s-manifest/overlays/prd/ 
          kustomize edit set image ${{ steps.login-ecr.outputs.registry }}/tmeroom-spring=${{ steps.login-ecr.outputs.registry }}/tmeroom-spring:${{ github.run_number }}.${{ github.run_attempt }}
          cat kustomization.yaml
      # 수정된 kustomization.yaml 파일 commit push
      - name: Commit and Push manfiest files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: yslee96
          author_email: dbstn322@gmail.com
          message: "🔧   : 스프링 서버 이미지 태그 업데이트 #${{ github.run_number }}.${{ github.run_attempt }}"
          cwd: './TMeRoom-k8s-manifest'
          push: true

      # 업로드한 artifacts를 삭제하기
      - name: Remove Github Actions Artifacts
        uses: GeekyEggo/delete-artifact@v2.0.0
        if: ${{ always() }}
        with:
          # The name of the artifact to delete; multiple names can be supplied on new lines.
          name: |
            env-file
            build-result
            Dockerfile
          
